language: php

services:
- docker

env:
  - UID=1000

before_install:
- docker-compose -f docker-compose-dev.yml build
- docker-compose -f docker-compose-dev.yml up -d
- docker ps -a
- docker-compose -f docker-compose-dev.yml run -e APP_ENV=testing build composer install
- docker-compose -f docker-compose-dev.yml run -e APP_ENV=testing build yarn install
- docker-compose -f docker-compose-dev.yml run -e APP_ENV=testing build yarn dev

script:
- docker-compose -f docker-compose-dev.yml run build ./artisan dusk --env=testing
