language: php

services:
- docker

env:
  - UID=1000 GID=1000

before_install:
- docker-compose -f docker-compose-dev.yml build
- cp app/.env.testing app/.env
- docker-compose -f docker-compose-dev.yml up -d --build
- docker ps -a
- docker-compose -f docker-compose-dev.yml run -e APP_ENV=testing build composer install
- docker-compose -f docker-compose-dev.yml run -e APP_ENV=testing build yarn install
- docker-compose -f docker-compose-dev.yml run -e APP_ENV=testing build yarn dev

script:
- docker-compose -f docker-compose-dev.yml run build ./artisan dusk --env=testing
## deactivate coverage check for now
## - docker-compose -f docker-compose-dev.yml run build yarn test-vue --coverage
- docker-compose -f docker-compose-dev.yml run build yarn test-vue
- docker-compose -f docker-compose-dev.yml run build yarn es-lint
- docker-compose -f docker-compose-dev.yml run build composer run-script cs-fixer -- --dry-run --verbose

## install database
- docker-compose -f docker-compose-dev.yml run build ./artisan migrate:refresh
- docker-compose -f docker-compose-dev.yml run build composer run-script phpunit
