version: '3'

services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./app:/app
    - ./docker/web/resources/site.conf:/etc/nginx/conf.d/site.conf
    links:
    - php
  php:
    image: php:7-fpm
    volumes:
    - ./app:/app
    user: "${UID}:${GID}"
  build:
    build:
      context: docker/build
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
    - ./app:/app
  selenium:
    image: selenium/standalone-chrome:3.141.59-antimony
    depends_on:
    - web
    volumes:
    - /dev/shm:/dev/shm