version: '3'

services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./app:/app
    - ./docker/web/resources/site.conf:/etc/nginx/conf.d/site.conf
    links:
    - php
  php:
    build:
      context: docker/php
    volumes:
    - ./app:/app
    user: "${UID}:${GID}"
    environment:
      TZ: "Etc/UTC"
      XDEBUG_CONFIG: remote_host=${LOCAL_IP}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: beautiful-home
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "beautiful-home"
    command:
      - mysqld
      - "--character-set-server=utf8mb4"
      - "--skip-character-set-client-handshake"
      - "--collation-server=utf8mb4_unicode_ci"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=db
    - PMA_USER=root
    - PMA_PASSWORD=root
  build:
    build:
      context: docker/build
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
    - ./app:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: beautiful-home
      DB_USERNAME: root
      DB_PASSWORD: root
  selenium:
    image: selenium/standalone-chrome:3.141.59-antimony
    depends_on:
    - web
    volumes:
    - /dev/shm:/dev/shm
