env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
globals:
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules:
  semi:
    - error
    - always
    - omitLastInOneLineBlock: false
  quotes:
    - "error"
    - "double"
  indent:
    - error
    - 4
  vue/html-indent:
    - error
    - 4
  vue/html-self-closing:
    - error
    - html:
        normal: any